#!/usr/bin/env python3
"""
Assemble individual SVG glyphs into a complete TrueType/OpenType font.

Takes SVG files generated by VecGlypher and uses fonttools to build
a proper .ttf font file with correct metrics and encoding.

Dependencies: fonttools, svgpathtools
"""

import argparse
import re
import sys
from pathlib import Path

try:
    from fontTools.fontBuilder import FontBuilder
    from fontTools.pens.t2Pen import T2Pen
    from fontTools.pens.pointPen import SegmentToPointPen
    from fontTools.ttLib import TTFont
    from fontTools.pens.recordingPen import RecordingPen
    from fontTools.svgLib.path import SVGPath
    import xml.etree.ElementTree as ET
except ImportError:
    print("Error: fonttools is required. Install with: pip install fonttools")
    sys.exit(1)

try:
    from svgpathtools import parse_path, Path as SVGPathToolsPath
except ImportError:
    print("Error: svgpathtools is required. Install with: pip install svgpathtools")
    sys.exit(1)


PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from configs.style_config import (
    FONT_DESCRIPTION,
    FONT_FAMILY,
    FONT_NAME,
    FONT_VERSION,
    SVG_CANVAS,
)


# Font metrics (in font units, typically UPM = 1000)
UPM = 1000  # Units per em
ASCENDER = 800
DESCENDER = -200
LINE_GAP = 0
DEFAULT_WIDTH = 600


def parse_svg_paths(svg_file: Path) -> list[str]:
    """Extract path 'd' attributes from an SVG file."""
    tree = ET.parse(svg_file)
    root = tree.getroot()
    ns = {"svg": "http://www.w3.org/2000/svg"}

    paths = []
    # Try with namespace
    for path_elem in root.findall(".//svg:path", ns):
        d = path_elem.get("d", "").strip()
        if d:
            paths.append(d)

    # Try without namespace
    if not paths:
        for path_elem in root.findall(".//{http://www.w3.org/2000/svg}path"):
            d = path_elem.get("d", "").strip()
            if d:
                paths.append(d)

    # Try plain (no namespace)
    if not paths:
        for path_elem in root.iter("path"):
            d = path_elem.get("d", "").strip()
            if d:
                paths.append(d)

    return paths


def svg_path_to_draw_commands(d_string: str, scale: float = 1.0, y_offset: float = 0) -> list:
    """Convert SVG path 'd' string to fonttools drawing commands.

    SVG coordinate system: y increases downward.
    Font coordinate system: y increases upward.
    We need to flip Y: font_y = UPM - svg_y (approximately).
    """
    path = parse_path(d_string)
    commands = []

    for segment in path:
        seg_type = type(segment).__name__

        if seg_type == "Line":
            start = segment.start
            end = segment.end
            # Flip Y axis for font coordinate system
            commands.append(
                (
                    "lineTo",
                    (
                        round(end.real * scale),
                        round((SVG_CANVAS["height"] - end.imag) * scale + y_offset),
                    ),
                )
            )
        elif seg_type == "CubicBezier":
            commands.append(
                (
                    "curveTo",
                    (
                        round(segment.control1.real * scale),
                        round((SVG_CANVAS["height"] - segment.control1.imag) * scale + y_offset),
                    ),
                    (
                        round(segment.control2.real * scale),
                        round((SVG_CANVAS["height"] - segment.control2.imag) * scale + y_offset),
                    ),
                    (
                        round(segment.end.real * scale),
                        round((SVG_CANVAS["height"] - segment.end.imag) * scale + y_offset),
                    ),
                )
            )
        elif seg_type == "QuadraticBezier":
            commands.append(
                (
                    "qCurveTo",
                    (
                        round(segment.control.real * scale),
                        round((SVG_CANVAS["height"] - segment.control.imag) * scale + y_offset),
                    ),
                    (
                        round(segment.end.real * scale),
                        round((SVG_CANVAS["height"] - segment.end.imag) * scale + y_offset),
                    ),
                )
            )
        elif seg_type == "Arc":
            # Approximate arc with line for simplicity
            commands.append(
                (
                    "lineTo",
                    (
                        round(segment.end.real * scale),
                        round((SVG_CANVAS["height"] - segment.end.imag) * scale + y_offset),
                    ),
                )
            )

    return commands


def draw_glyph(pen, svg_paths: list[str], scale: float = 1.0):
    """Draw all SVG paths as a single glyph using a fonttools pen."""
    for d_string in svg_paths:
        path = parse_path(d_string)
        if not path:
            continue

        # Get the starting point
        start = path[0].start
        pen.moveTo(
            (
                round(start.real * scale),
                round((SVG_CANVAS["height"] - start.imag) * scale),
            )
        )

        for segment in path:
            seg_type = type(segment).__name__

            if seg_type == "Line":
                pen.lineTo(
                    (
                        round(segment.end.real * scale),
                        round((SVG_CANVAS["height"] - segment.end.imag) * scale),
                    )
                )
            elif seg_type == "CubicBezier":
                pen.curveTo(
                    (
                        round(segment.control1.real * scale),
                        round((SVG_CANVAS["height"] - segment.control1.imag) * scale),
                    ),
                    (
                        round(segment.control2.real * scale),
                        round((SVG_CANVAS["height"] - segment.control2.imag) * scale),
                    ),
                    (
                        round(segment.end.real * scale),
                        round((SVG_CANVAS["height"] - segment.end.imag) * scale),
                    ),
                )
            elif seg_type == "QuadraticBezier":
                pen.qCurveTo(
                    (
                        round(segment.control.real * scale),
                        round((SVG_CANVAS["height"] - segment.control.imag) * scale),
                    ),
                    (
                        round(segment.end.real * scale),
                        round((SVG_CANVAS["height"] - segment.end.imag) * scale),
                    ),
                )
            elif seg_type == "Arc":
                pen.lineTo(
                    (
                        round(segment.end.real * scale),
                        round((SVG_CANVAS["height"] - segment.end.imag) * scale),
                    )
                )

        # Close the path (if it's a closed subpath)
        if path.isclosed():
            pen.closePath()
        else:
            pen.endPath()


def extract_char_from_filename(filename: str) -> str | None:
    """Extract character from SVG filename like 'u0410_А.svg'."""
    # Pattern: u{hex}_{char}.svg
    match = re.match(r"u([0-9a-f]+)_(.+)\.svg", filename, re.IGNORECASE)
    if match:
        return match.group(2)

    # Try to decode from hex in filename
    match = re.match(r"u([0-9a-f]+)", filename, re.IGNORECASE)
    if match:
        try:
            return chr(int(match.group(1), 16))
        except ValueError:
            pass

    return None


def build_font(svg_dir: Path, output_path: Path):
    """Build a TrueType font from SVG glyph files."""
    # Collect SVG files and map to characters
    glyph_map: dict[str, Path] = {}

    for svg_file in sorted(svg_dir.glob("*.svg")):
        char = extract_char_from_filename(svg_file.name)
        if char and len(char) == 1:
            glyph_map[char] = svg_file

    if not glyph_map:
        print("Error: No valid SVG glyph files found!")
        return False

    print(f"Found {len(glyph_map)} glyphs to include")

    # Calculate scale factor: SVG canvas -> font UPM
    scale = UPM / SVG_CANVAS["height"]

    # Build glyph names and unicode map
    glyph_names = [".notdef", "space"]
    char_map = {32: "space"}  # space character

    for char in sorted(glyph_map.keys()):
        codepoint = ord(char)
        glyph_name = f"uni{codepoint:04X}"
        glyph_names.append(glyph_name)
        char_map[codepoint] = glyph_name

    # Create font builder
    fb = FontBuilder(UPM, isTTF=True)
    fb.setupGlyphOrder(glyph_names)
    fb.setupCharacterMap(char_map)

    # Draw glyphs
    fb.setupGlyf({})
    font = fb.font
    glyf_table = font["glyf"]

    # We need to use the pen interface to draw glyphs
    glyph_table = font["glyf"]

    # Set up metrics
    metrics = {}
    metrics[".notdef"] = (UPM, 0)
    metrics["space"] = (DEFAULT_WIDTH, 0)

    print("Drawing glyphs...")
    for char, svg_file in sorted(glyph_map.items()):
        codepoint = ord(char)
        glyph_name = f"uni{codepoint:04X}"

        svg_paths = parse_svg_paths(svg_file)
        if not svg_paths:
            print(f"  Warning: No paths in {svg_file.name}, using empty glyph")
            metrics[glyph_name] = (DEFAULT_WIDTH, 0)
            continue

        # Record the drawing
        rec_pen = RecordingPen()
        draw_glyph(rec_pen, svg_paths, scale)

        # Replay into the glyf table
        tt_pen = glyf_table.getPen(font.getGlyphSet(), glyph_name)
        rec_pen.replay(tt_pen)

        metrics[glyph_name] = (DEFAULT_WIDTH, 0)
        print(f"  {char} ({glyph_name}) - {len(svg_paths)} path(s)")

    # Setup horizontal metrics
    fb.setupHorizontalMetrics(metrics)

    # Setup horizontal header
    fb.setupHorizontalHeader(ascent=ASCENDER, descent=DESCENDER)

    # Setup name table
    fb.setupNameTable(
        {
            "familyName": FONT_FAMILY,
            "styleName": "Regular",
            "psName": FONT_NAME + "-Regular",
            "uniqueFontIdentifier": f"{FONT_NAME};{FONT_VERSION}",
            "version": f"Version {FONT_VERSION}",
            "description": FONT_DESCRIPTION,
        }
    )

    # Setup OS/2 table
    fb.setupOs2(
        sTypoAscender=ASCENDER,
        sTypoDescender=DESCENDER,
        sTypoLineGap=LINE_GAP,
        usWinAscent=ASCENDER,
        usWinDescent=abs(DESCENDER),
        sxHeight=500,
        sCapHeight=700,
        # Cyrillic code page
        ulCodePageRange1=(1 << 2),  # Cyrillic
    )

    # Setup post table
    fb.setupPost()

    # Save
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fb.font.save(str(output_path))
    print(f"\nFont saved to: {output_path}")
    return True


def main():
    parser = argparse.ArgumentParser(
        description="Assemble SVG glyphs into a TrueType font"
    )
    parser.add_argument(
        "--style",
        default="default",
        help="Style variant name (matches SVG directory name)",
    )
    parser.add_argument(
        "--svg-dir",
        type=Path,
        default=None,
        help="Override SVG directory path",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Override output font file path",
    )
    parser.add_argument(
        "--format",
        choices=["ttf", "otf"],
        default="ttf",
        help="Output font format (default: ttf)",
    )

    args = parser.parse_args()

    svg_dir = args.svg_dir or PROJECT_ROOT / "output" / "svgs" / args.style
    if args.output:
        output_path = args.output
    else:
        suffix = "Regular"
        output_path = (
            PROJECT_ROOT / "output" / "font" / f"{FONT_NAME}-{suffix}.{args.format}"
        )

    if not svg_dir.exists():
        print(f"Error: SVG directory not found: {svg_dir}")
        print("Run inference first to generate SVG glyphs.")
        sys.exit(1)

    print(f"=== Assembling Font: {FONT_NAME} ===")
    print(f"SVG source: {svg_dir}")
    print(f"Output:     {output_path}")
    print()

    success = build_font(svg_dir, output_path)
    if success:
        print(f"\n=== Font Assembly Complete ===")
        print(f"Install the font: {output_path}")
    else:
        print("\nFont assembly failed.")
        sys.exit(1)


if __name__ == "__main__":
    main()
